### PR TITLE
Add reserved usernames

### PR DESCRIPTION
**Pull request by hikaru-light**
I suggest reserving these words "system, official, owner, master, register, staff, support, admin, etc.".
At least, I added them as reserved usernames in developing another service.
Please let me know your opinions on this.

### CODE REVIEW

**Comment by hikaru-light** [comment]
Sorry, I will change the way to implement this.
So, this is WIP.

**Comment by hikaru-light** [comment]
Please check this.

**Comment by hikaru-light** [comment]
There's a Travis CI error.:confused:

**Comment by masarakki** [comment]
it is better to use this gem (https://github.com/kwappa/username_not_reserved_validator), 
but... I think it's too late to do...

**Comment by hikaru-light** [comment]
@masarakki Thank you for your nice advice. I'm going to try using it.:+1:

**Pull request closed without merging**
